# This GitHub Actions workflow automates CI for the STM32 bare-metal project.
# It runs code quality checks using clang-format and clang-tidy, then builds the project in a Docker container.
# The workflow triggers on pushes to 'main' and all pull requests.
# 
# Jobs:
# - code-quality: Checks code formatting and static analysis.
# - build: Builds the project using Docker after code-quality passes.

name: Bare-Metal CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "**" ]

jobs:
    code-quality:
        name: "Code Quality Check"
        runs-on: ubuntu-latest
        
        steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Install Clang Tools
          run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy

        - name: Run clang-format check
          run: clang-format --dry-run -Werror $(find . -name "*.c" -or -name "*.h")

        - name: Run clang-tidy check
          run: clang-tidy $(find . -name "*.c") -- -I./Drivers/CMSIS/Include -I./Drivers/CMSIS/Device/ST/STM32F1xx/Include -I./src -DSTM32F103xB


    build: 
      name: Build with Docker
      needs: code-quality
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v4 #latest 
        - name: Build Docker image
          run: docker build -t stm32-builder .
        - name: Run make inside container
          run: docker run --rm stm32-builder make